import type { EngineeringBacklogItem } from './engineeringTaskTypes';
import type { EngineeringIssueDraft } from './engineeringIssueTypes';

export function buildIssueBodyMarkdown(draft: Omit<EngineeringIssueDraft, 'bodyMarkdown'>, sourceItems: EngineeringBacklogItem[]): string {
  const recommendedActions = [...new Set(sourceItems.map((item) => item.recommendedAction))];
  return `## Summary

${summaryForDraft(draft, sourceItems)}

## Why this matters

${whyItMatters(draft)}

## Affected area

- Repo: ${draft.repo}
- Owner: ${draft.owner}
- Feature area: ${draft.featureArea}
- Severity: ${draft.severity}
- Effort: ${draft.effort}

## Source backlog items

${sourceItems.map((item) => `- [ ] ${item.title}`).join('\n')}

## Recommended action

${recommendedActions.map((action) => `- ${action}`).join('\n')}

## Validation checklist

- [ ] Review affected files/nodes
- [ ] Confirm no production behavior changes unless intended
- [ ] Add or update docs/tests if needed
- [ ] Run build/lint/typecheck where appropriate

## Safety notes

This issue was generated by the Vyra Engineering Agent as a draft. It has not modified code, production data, or GitHub state.
`;
}

function summaryForDraft(draft: Omit<EngineeringIssueDraft, 'bodyMarkdown'>, sourceItems: EngineeringBacklogItem[]): string {
  return `${draft.title}. This draft groups ${sourceItems.length} Engineering Fix Queue item${sourceItems.length === 1 ? '' : 's'} for Robert to review before any GitHub issue is created.`;
}

function whyItMatters(draft: Omit<EngineeringIssueDraft, 'bodyMarkdown'>): string {
  if (draft.category === 'documentation') return 'Documentation gaps make ownership, safe operation, and future implementation planning harder to verify.';
  if (draft.category === 'cleanup') return 'Orphan candidates can indicate stale or disconnected code, but they require manual confirmation before any cleanup is proposed.';
  if (draft.category === 'investigation') return 'Broken graph relationships can hide missing dependencies, missing env examples, or incomplete migration/function visibility.';
  if (draft.category === 'repo-health') return 'Repo health planning helps prioritize the largest advisory risk clusters before implementation work.';
  return 'High-risk nodes should have explicit ownership, impact review, and validation planning before changes are proposed.';
}
