import type { GitHubRepositoryStatus } from './githubTypes';

export const githubRepositoryStatuses: GitHubRepositoryStatus[] = [
  {
    repositoryName: 'Vyra-Part-1',
    remoteUrl: 'https://github.com/Matthewalbin1/Vyra-Part-1',
    defaultBranch: 'main',
    latestCommit: 'remote synced through 20260628193000 migrations',
    latestCommitMessage: 'Add agent memory and gym migration foundation tables',
    latestCommitDate: '2026-06-29T00:02:00Z',
    openPullRequests: 0,
    issueCount: 4,
    workflowStatus: 'Read-only checks planned',
    workflowConclusion: 'mock',
    lastUpdated: '2026-06-28 21:55 ET',
    healthStatus: 'warning',
  },
  {
    repositoryName: 'Vyra-Software',
    remoteUrl: 'pending local remote discovery',
    defaultBranch: 'main',
    latestCommit: 'mock status',
    latestCommitMessage: 'Mock repository status',
    latestCommitDate: 'Mock readiness only',
    openPullRequests: 0,
    issueCount: 1,
    workflowStatus: 'Not connected',
    workflowConclusion: 'mock',
    lastUpdated: '2026-06-28 21:55 ET',
    healthStatus: 'prepared',
  },
  {
    repositoryName: 'vyra-website',
    remoteUrl: 'pending local remote discovery',
    defaultBranch: 'main',
    latestCommit: 'mock status',
    latestCommitMessage: 'Mock repository status',
    latestCommitDate: 'Mock readiness only',
    openPullRequests: 0,
    issueCount: 2,
    workflowStatus: 'Not connected',
    workflowConclusion: 'mock',
    lastUpdated: '2026-06-28 21:55 ET',
    healthStatus: 'prepared',
  },
  {
    repositoryName: 'vyra-agents',
    remoteUrl: 'https://github.com/unpaidintern9/vyra-agents',
    defaultBranch: 'main',
    latestCommit: '91dcfd2',
    latestCommitMessage: 'Add read-only integration foundation',
    latestCommitDate: '2026-06-29T01:55:00Z',
    openPullRequests: 0,
    issueCount: 0,
    workflowStatus: 'Local validation passing',
    workflowConclusion: 'mock',
    lastUpdated: '2026-06-28 21:55 ET',
    healthStatus: 'healthy',
  },
];
