import type { ProposalPrep, SalesActivity, SalesLead } from './salesTypes';

export const salesMockLeads: SalesLead[] = [
  {
    id: 'lead_river_city_bjj',
    leadType: 'gym',
    name: 'River City BJJ',
    businessName: 'River City BJJ',
    contactName: 'Avery Knox',
    email: 'avery@example.local',
    phone: '555-0142',
    location: 'Louisville, KY',
    source: 'Robert referral',
    status: 'active',
    pipelineStage: 'qualified',
    estimatedValue: 14400,
    priority: 'high',
    nextAction: 'Prepare migration and platform proposal',
    nextFollowUpDate: todayOffset(-1),
    notes: 'Gym wants a smoother onboarding path for 180 active members.',
    memberCount: 180,
    likelyProductFit: 'Gym dashboard + member app',
    createdAt: todayOffset(-12),
    updatedAt: todayOffset(-1),
  },
  {
    id: 'lead_northstar_fitness',
    leadType: 'gym',
    name: 'Northstar Fitness Collective',
    businessName: 'Northstar Fitness Collective',
    contactName: 'Mina Chen',
    email: 'mina@example.local',
    phone: '555-0198',
    location: 'Cincinnati, OH',
    source: 'Website waitlist',
    status: 'active',
    pipelineStage: 'demo_scheduled',
    estimatedValue: 9600,
    priority: 'medium',
    nextAction: 'Confirm demo agenda and data migration questions',
    nextFollowUpDate: todayOffset(2),
    notes: 'Interested in memberships, attendance, and lightweight billing handoff.',
    memberCount: 95,
    likelyProductFit: 'Gym dashboard',
    createdAt: todayOffset(-8),
    updatedAt: todayOffset(-2),
  },
  {
    id: 'lead_coach_marcus',
    leadType: 'coach',
    name: 'Marcus Hill Coaching',
    businessName: 'Marcus Hill Coaching',
    contactName: 'Marcus Hill',
    email: 'marcus@example.local',
    phone: '555-0177',
    location: 'Remote',
    source: 'Instagram DM',
    status: 'active',
    pipelineStage: 'proposal_needed',
    estimatedValue: 3600,
    priority: 'high',
    nextAction: 'Draft coach plan quote',
    nextFollowUpDate: todayOffset(0),
    notes: 'Needs client accountability, training notes, and simple payments later.',
    currentClients: 24,
    niche: 'Strength and conditioning',
    likelyProductFit: 'Independent coach plan',
    createdAt: todayOffset(-5),
    updatedAt: todayOffset(0),
  },
  {
    id: 'lead_powerhouse_referral',
    leadType: 'referral',
    name: 'Powerhouse referral batch',
    businessName: 'Powerhouse Performance',
    contactName: 'Jamie Ortiz',
    email: 'jamie@example.local',
    phone: '555-0133',
    location: 'Lexington, KY',
    source: 'Partner referral',
    status: 'active',
    pipelineStage: 'new',
    estimatedValue: 7200,
    priority: 'medium',
    nextAction: 'Qualify business model and owner goals',
    nextFollowUpDate: null,
    notes: 'Referral from a current operator; needs qualification.',
    createdAt: todayOffset(-2),
    updatedAt: todayOffset(-2),
  },
  {
    id: 'lead_coach_elena',
    leadType: 'coach',
    name: 'Elena Ruiz Mobility',
    businessName: 'Elena Ruiz Mobility',
    contactName: 'Elena Ruiz',
    email: 'elena@example.local',
    phone: '555-0164',
    location: 'Nashville, TN',
    source: 'Workshop signup',
    status: 'paused',
    pipelineStage: 'paused',
    estimatedValue: 2400,
    priority: 'low',
    nextAction: 'Revisit after summer programming',
    nextFollowUpDate: todayOffset(20),
    notes: 'Interested but not ready this month.',
    currentClients: 12,
    niche: 'Mobility coaching',
    likelyProductFit: 'Coach starter plan',
    createdAt: todayOffset(-18),
    updatedAt: todayOffset(-4),
  },
  {
    id: 'lead_summit_wellness',
    leadType: 'organization',
    name: 'Summit Wellness Group',
    businessName: 'Summit Wellness Group',
    contactName: 'Nora Patel',
    email: 'nora@example.local',
    phone: '555-0119',
    location: 'Columbus, OH',
    source: 'Outbound list',
    status: 'won',
    pipelineStage: 'won',
    estimatedValue: 18000,
    priority: 'high',
    nextAction: 'Prepare onboarding readiness checklist',
    nextFollowUpDate: todayOffset(5),
    notes: 'Mock won account for monthly summary display only.',
    likelyProductFit: 'Organization platform',
    createdAt: todayOffset(-22),
    updatedAt: todayOffset(-3),
  },
];

export const salesMockActivities: SalesActivity[] = [
  {
    id: 'sales_activity_river_city',
    leadId: 'lead_river_city_bjj',
    activityType: 'follow_up',
    summary: 'Follow-up due for River City BJJ proposal prep.',
    timestamp: todayOffset(-1),
    outcome: 'Needs proposal',
    nextAction: 'Prepare migration and platform proposal',
  },
  {
    id: 'sales_activity_marcus',
    leadId: 'lead_coach_marcus',
    activityType: 'proposal',
    summary: 'Coach lead moved into proposal-needed status.',
    timestamp: todayOffset(0),
    outcome: 'Quote prep required',
    nextAction: 'Draft coach plan quote',
  },
  {
    id: 'sales_activity_northstar',
    leadId: 'lead_northstar_fitness',
    activityType: 'note',
    summary: 'Northstar demo scheduled; migration questions captured.',
    timestamp: todayOffset(-2),
    outcome: 'Demo agenda ready',
    nextAction: 'Confirm demo agenda',
  },
];

export const salesMockProposals: ProposalPrep[] = [
  {
    leadId: 'lead_river_city_bjj',
    recommendedProduct: 'Gym dashboard + member app',
    pricingTier: 'Growth Gym',
    setupFee: 1500,
    monthlyFee: 1200,
    migrationFee: 900,
    migrationNeeded: true,
    notes: 'Include migration audit, member import, and owner review checklist.',
    status: 'needed',
  },
  {
    leadId: 'lead_coach_marcus',
    recommendedProduct: 'Independent coach plan',
    pricingTier: 'Coach Pro',
    setupFee: 250,
    monthlyFee: 300,
    migrationFee: 0,
    migrationNeeded: false,
    notes: 'Quote should cover client tracker, programming notes, and future payment boundary.',
    status: 'needed',
  },
];

function todayOffset(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}
