import type { LocalReport } from '../../storage/reportExport';
import type {
  SalesDuplicateCandidate,
  SalesEnrichmentHistoryItem,
  SalesOpportunity,
  SalesResearchIntakeItem,
  SalesResearchIntelligenceSummary,
  SalesResearchSource,
} from './salesTypes';

const generatedAt = '2026-07-01T12:30:00.000Z';

export function createInitialSalesResearchSources(): SalesResearchSource[] {
  return [
    source('src-manual-notes', 'Manual Operator Notes', 'Manual Research', 'Operator pasted public/manual notes.', true, 'Manual', 'Local', false, 92, 88, 'Approved'),
    source('src-public-website', 'Public Website Review', 'Public Website', 'Operator-reviewed public website fields only.', true, 'Manual', 'External', false, 84, 78, 'Approved'),
    source('src-local-reports', 'Existing Sales Reports', 'Existing Reports', 'Local reports generated by Sales Agent.', true, 'Semi-Automatic', 'Local', false, 88, 84, 'Approved'),
    source('src-linkedin-manual', 'LinkedIn Manual Reference', 'LinkedIn (manual reference only)', 'Manual reference only. No scraping or automation.', false, 'Manual', 'External', true, 65, 52, 'Pending Review'),
    source('src-state-registry', 'Kentucky State Registry Manual Lookup', 'State Registry', 'Manual state registry checks when pasted by operator.', false, 'Manual', 'External', false, 80, 62, 'Draft'),
    source('src-csv-import', 'Local CSV Import', 'CSV Import', 'Local CSV files reviewed before scoring.', true, 'Semi-Automatic', 'Local', false, 74, 70, 'Approved'),
  ];
}

export function createInitialSalesResearchIntake(opportunities: SalesOpportunity[]): SalesResearchIntakeItem[] {
  return opportunities.slice(0, 6).map((opportunity, index) => intake(opportunity, index));
}

export function createInitialSalesEnrichmentHistory(opportunities: SalesOpportunity[]): SalesEnrichmentHistoryItem[] {
  return opportunities.slice(0, 4).map((opportunity, index) => ({
    confidence: 78 + index,
    field: 'companySizeEstimate',
    id: `enrich-${opportunity.id}`,
    newValue: opportunity.companySizeEstimate,
    operator: 'Sales Agent',
    opportunityId: opportunity.id,
    previousValue: 'Unknown',
    reason: 'Seeded from approved local/manual research for Phase 48.',
    sourceId: index % 2 === 0 ? 'src-manual-notes' : 'src-public-website',
    timestamp: generatedAt,
  }));
}

export function summarizeSalesResearchIntelligence(
  sources: SalesResearchSource[],
  intakeQueue: SalesResearchIntakeItem[],
  enrichmentHistory: SalesEnrichmentHistoryItem[],
): SalesResearchIntelligenceSummary {
  const approvedSources = sources.filter((source) => source.approvalStatus === 'Approved' && source.enabled).length;
  return {
    approvedSources,
    confidenceTrend: average([...sources.map((source) => source.confidenceScore), ...intakeQueue.map((item) => item.confidence)]),
    duplicateAlerts: intakeQueue.reduce((count, item) => count + item.duplicateDetection.length, 0),
    enrichmentProgress: Math.round((enrichmentHistory.length / Math.max(1, intakeQueue.length)) * 100),
    pendingReviews: sources.filter((source) => source.approvalStatus === 'Pending Review' || source.approvalStatus === 'Draft').length + intakeQueue.filter((item) => item.reviewStatus === 'pending_review').length,
    rejectedSources: sources.filter((source) => source.approvalStatus === 'Rejected').length,
    researchBacklog: intakeQueue.filter((item) => item.reviewStatus === 'pending_review').length,
    verificationQueue: intakeQueue.filter((item) => item.verificationStatus !== 'verified' || item.humanReviewRequired).length,
  };
}

export function buildSalesResearchReports(
  sources: SalesResearchSource[],
  intakeQueue: SalesResearchIntakeItem[],
  enrichmentHistory: SalesEnrichmentHistoryItem[],
): Record<string, LocalReport> {
  const summary = summarizeSalesResearchIntelligence(sources, intakeQueue, enrichmentHistory);
  return {
    confidenceTrend: report('Confidence Trend Report', sources.map((source) => ({ source: source.name, confidence: source.confidenceScore, trust: source.trustScore })), summary),
    duplicateAnalysis: report('Duplicate Analysis', intakeQueue.flatMap((item) => item.duplicateDetection), summary),
    enrichment: report('Opportunity Enrichment Report', enrichmentHistory, summary),
    executiveIntelligence: report('Executive Intelligence Summary', [summary], summary),
    intake: report('Research Intake Report', intakeQueue, summary),
    sourceInventory: report('Source Inventory', sources, summary),
    sourceUtilization: report('Source Utilization Report', sources.map((source) => ({ source: source.name, lastUsedAt: source.lastUsedAt, enabled: source.enabled, approvalStatus: source.approvalStatus })), summary),
    verification: report('Verification Report', intakeQueue.map((item) => ({ company: item.company, confidence: item.confidence, evidenceLevel: item.evidenceLevel, completeness: item.completeness, riskRating: item.riskRating, reviewStatus: item.reviewStatus, missingInformation: item.missingInformation.join('; ') })), summary),
  };
}

function source(
  id: string,
  name: SalesResearchSource['name'],
  category: SalesResearchSource['category'],
  description: string,
  enabled: boolean,
  mode: SalesResearchSource['mode'],
  scope: SalesResearchSource['scope'],
  authenticationRequired: boolean,
  trustScore: number,
  confidenceScore: number,
  approvalStatus: SalesResearchSource['approvalStatus'],
): SalesResearchSource {
  return {
    approvalStatus,
    authenticationRequired,
    category,
    confidenceScore,
    createdAt: generatedAt,
    description,
    enabled,
    id,
    lastUsedAt: approvalStatus === 'Approved' ? generatedAt : null,
    mode,
    name,
    notes: ['Local source record only. Automatic source approval is disabled.'],
    scope,
    status: approvalStatus === 'Approved' && enabled ? 'active' : 'needs_review',
    trustScore,
    updatedAt: generatedAt,
  };
}

function intake(opportunity: SalesOpportunity, index: number): SalesResearchIntakeItem {
  const duplicateDetection: SalesDuplicateCandidate[] =
    index === 1
      ? [
          {
            confidence: 86,
            detectedAt: generatedAt,
            fields: ['company', 'website'],
            id: `dup-${opportunity.id}`,
            reason: 'Company and website resemble an existing local opportunity.',
            suggestedMergeAction: 'Review manually and merge only after operator approval.',
            targetId: opportunity.id,
            targetType: 'opportunity',
          },
        ]
      : [];
  return {
    analyst: 'Sales Agent',
    company: opportunity.company,
    completeness: 68 + index * 3,
    confidence: 72 + index * 4,
    date: generatedAt,
    duplicateDetection,
    evidenceLevel: index < 2 ? 'high' : index < 4 ? 'medium' : 'low',
    humanReviewRequired: index > 2 || duplicateDetection.length > 0,
    id: `intake-${opportunity.id}`,
    missingInformation: ['verified contact', 'current software', 'decision maker'],
    opportunityId: opportunity.id,
    rawNotes: `Manual/public research notes for ${opportunity.company}.`,
    researchType: index % 2 === 0 ? 'company profile' : 'contact path',
    reviewStatus: index < 2 ? 'approved' : 'pending_review',
    riskRating: index > 3 ? 'medium' : 'low',
    sourceId: index % 2 === 0 ? 'src-manual-notes' : 'src-public-website',
    suggestedActions: ['Verify contact path', 'Update opportunity notes', 'Queue follow-up after review'],
    summary: `${opportunity.company} research intake prepared from approved local/manual source.`,
    verificationStatus: index < 2 ? 'verified' : 'partially_verified',
  };
}

function report(title: string, rows: object[], summary: SalesResearchIntelligenceSummary): LocalReport {
  return {
    title,
    slug: title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
    summary: { ...summary, localOnly: true, safety: 'No autonomous browsing, messaging, CRM sync, or source approval.' },
    rows,
  };
}

function average(values: number[]) {
  if (!values.length) return 0;
  return Math.round(values.reduce((sum, value) => sum + value, 0) / values.length);
}
