import type { WorkflowDefinition } from './workflowTypes';

export const workflowMockData: WorkflowDefinition[] = [
  {
    key: 'daily-ecosystem-audit',
    triggerType: 'scheduled',
    ownerAgent: 'Executive Agent',
    currentMode: 'mock/local',
    lastRun: 'Not run in Phase 5',
    nextStatus: 'ready for dry check',
    riskLevel: 'low',
    approvalRequired: false,
    safeDryRun: true,
  },
  {
    key: 'repo-health-check',
    triggerType: 'manual refresh',
    ownerAgent: 'Engineering Agent',
    currentMode: 'read-only',
    lastRun: 'Last integration refresh',
    nextStatus: 'ready',
    riskLevel: 'low',
    approvalRequired: false,
    safeDryRun: true,
  },
  {
    key: 'engineering-knowledge-graph-scan',
    triggerType: 'manual',
    ownerAgent: 'Engineering Agent',
    currentMode: 'read-only',
    lastRun: 'Latest generated graph',
    nextStatus: 'ready',
    riskLevel: 'low',
    approvalRequired: false,
    safeDryRun: true,
  },
  {
    key: 'engineering-impact-analysis',
    triggerType: 'manual export',
    ownerAgent: 'Engineering Agent',
    currentMode: 'read-only',
    lastRun: 'Node detail or impact export',
    nextStatus: 'ready',
    riskLevel: 'low',
    approvalRequired: false,
    safeDryRun: true,
  },
  {
    key: 'engineering-ownership-health-scan',
    triggerType: 'manual scan/report',
    ownerAgent: 'Engineering Agent',
    currentMode: 'read-only',
    lastRun: 'Ownership or health report export',
    nextStatus: 'ready',
    riskLevel: 'low',
    approvalRequired: false,
    safeDryRun: true,
  },
  {
    key: 'engineering-fix-queue-planning',
    triggerType: 'local planning',
    ownerAgent: 'Engineering Agent',
    currentMode: 'read-only',
    lastRun: 'Fix queue status or backlog export',
    nextStatus: 'ready',
    riskLevel: 'low',
    approvalRequired: false,
    safeDryRun: true,
  },
  {
    key: 'engineering-github-issue-draft-planning',
    triggerType: 'local issue draft',
    ownerAgent: 'Engineering Agent',
    currentMode: 'read-only',
    lastRun: 'Issue draft status or export',
    nextStatus: 'approval required before future GitHub creation',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'engineering-github-issue-creation',
    triggerType: 'approval-gated GitHub write',
    ownerAgent: 'Engineering Agent',
    currentMode: 'read-only',
    lastRun: 'Dry-run only until explicitly enabled',
    nextStatus: 'approval required before live GitHub write',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'integration-status-check',
    triggerType: 'manual refresh',
    ownerAgent: 'Operations Agent',
    currentMode: 'read-only',
    lastRun: 'Last integration refresh',
    nextStatus: 'ready',
    riskLevel: 'low',
    approvalRequired: false,
    safeDryRun: true,
  },
  {
    key: 'migration-import-review',
    triggerType: 'manual',
    ownerAgent: 'Migration Agent',
    currentMode: 'mock/local',
    lastRun: 'Seeded mock run',
    nextStatus: 'gym review',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'migration-validation',
    triggerType: 'manual',
    ownerAgent: 'Migration Agent',
    currentMode: 'mock/local',
    lastRun: 'Seeded mock run',
    nextStatus: 'ready for dry run',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'migration-member-matching',
    triggerType: 'manual',
    ownerAgent: 'Migration Agent',
    currentMode: 'mock/local',
    lastRun: 'Not run in Phase 5',
    nextStatus: 'ready for dry check',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'migration-batch-preview',
    triggerType: 'manual',
    ownerAgent: 'Migration Agent',
    currentMode: 'mock/local',
    lastRun: 'Local batch builder preview',
    nextStatus: 'approval packet review',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'approval-queue-review',
    triggerType: 'manual',
    ownerAgent: 'Operations Agent',
    currentMode: 'mock/local',
    lastRun: 'Not run in Phase 5',
    nextStatus: 'pending review',
    riskLevel: 'high',
    approvalRequired: true,
    safeDryRun: false,
  },
  {
    key: 'sales-lead-review',
    triggerType: 'manual',
    ownerAgent: 'Sales Agent',
    currentMode: 'mock/local',
    lastRun: 'Not run in Phase 18',
    nextStatus: 'placeholder registered',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'support-ticket-review',
    triggerType: 'manual',
    ownerAgent: 'Support Agent',
    currentMode: 'mock/local',
    lastRun: 'Not run in Phase 18',
    nextStatus: 'placeholder registered',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'finance-report-review',
    triggerType: 'manual',
    ownerAgent: 'Finance Agent',
    currentMode: 'mock/local',
    lastRun: 'Not run in Phase 18',
    nextStatus: 'placeholder registered',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'marketing-campaign-review',
    triggerType: 'manual',
    ownerAgent: 'Marketing Agent',
    currentMode: 'mock/local',
    lastRun: 'Not run in Phase 18',
    nextStatus: 'placeholder registered',
    riskLevel: 'medium',
    approvalRequired: true,
    safeDryRun: true,
  },
  {
    key: 'product-surface-review',
    triggerType: 'manual',
    ownerAgent: 'Product Agent',
    currentMode: 'mock/local',
    lastRun: 'Not run in Phase 18',
    nextStatus: 'placeholder registered',
    riskLevel: 'low',
    approvalRequired: false,
    safeDryRun: true,
  },
];
