import type { ExistingVyraUser, ImportedMember, MigrationBatch } from './migrationTypes';

export const migrationBatch: MigrationBatch = {
  gymName: 'Derby City Martial Arts',
  organizationId: 'derby-city-123',
  source: 'CSV Upload',
  status: 'Validation Review',
  importedMembers: 1284,
  createdBy: 'Migration Agent',
};

export const existingVyraUsers: ExistingVyraUser[] = [
  {
    userId: 'usr_1029',
    displayName: 'Maya Chen',
    email: 'maya.chen@example.com',
    phone: '+15025550112',
  },
  {
    userId: 'usr_2044',
    displayName: 'Andre Wilson',
    email: 'andre.wilson@example.com',
    phone: '+15025550113',
  },
  {
    userId: 'usr_3110',
    displayName: 'Sam Rivera',
    email: 'sam.rivera@example.com',
    phone: '+15025550114',
  },
];

export const importedMembers: ImportedMember[] = [
  {
    id: 'stg_001',
    externalMemberId: 'DCMA-1001',
    firstName: 'Maya',
    lastName: 'Chen',
    email: 'maya.chen@example.com',
    phone: '+15025550112',
    dateOfBirth: '1992-04-18',
    membershipStatus: 'active',
    membershipType: 'Unlimited',
    membershipLevel: 'Blue Belt',
    membershipStartDate: '2021-01-12',
    renewalDate: '2026-12-01',
    billingStatus: 'current',
    coachAssignment: 'Coach Price',
    classEnrollments: ['Adult BJJ', 'No-Gi Fundamentals'],
    possibleExistingVyraUser: true,
  },
  {
    id: 'stg_002',
    externalMemberId: 'DCMA-1002',
    firstName: 'Jonah',
    lastName: 'Price',
    email: 'jonah.price@example.com',
    phone: '+15025550115',
    dateOfBirth: '1988-07-09',
    membershipStatus: 'active',
    membershipType: 'Family',
    membershipLevel: 'White Belt',
    membershipStartDate: '2023-05-19',
    renewalDate: '2026-09-15',
    billingStatus: 'current',
    familyAccountId: 'fam_price',
    wantsAppAccess: true,
  },
  {
    id: 'stg_003',
    externalMemberId: 'DCMA-1003',
    firstName: 'Lena',
    lastName: 'Price',
    email: 'jonah.price@example.com',
    phone: '+15025550116',
    dateOfBirth: '2014-02-21',
    membershipStatus: 'active',
    membershipType: 'Youth',
    membershipLevel: 'Gray Belt',
    membershipStartDate: '2024-01-03',
    renewalDate: '2026-09-15',
    billingStatus: 'family plan',
    familyAccountId: 'fam_price',
    possibleChildAccount: true,
    wantsAppAccess: false,
  },
  {
    id: 'stg_004',
    externalMemberId: 'DCMA-1004',
    firstName: 'Andre',
    lastName: 'Wilson',
    email: 'andre.wilson@example.com',
    phone: '+15025550113',
    dateOfBirth: '1984-11-02',
    membershipStatus: 'frozen',
    membershipType: 'Unlimited',
    membershipLevel: 'Purple Belt',
    membershipStartDate: '2019-03-14',
    renewalDate: '2026-08-01',
    billingStatus: 'paused',
    possibleExistingVyraUser: true,
  },
  {
    id: 'stg_005',
    externalMemberId: 'DCMA-1005',
    firstName: 'Ruth',
    lastName: 'Ellis',
    phone: '+15025550117',
    dateOfBirth: '1972-06-10',
    membershipStatus: 'active',
    membershipType: 'Morning Classes',
    membershipLevel: 'Black Belt',
    membershipStartDate: '2018-09-01',
    renewalDate: '2027-01-01',
    billingStatus: 'current',
    knownOffline: true,
    notes: 'Prefers front-desk check-in and phone communication.',
  },
  {
    id: 'stg_006',
    externalMemberId: 'DCMA-1006',
    firstName: '',
    lastName: 'Morgan',
    email: 'morgan.invalid',
    phone: '555-ABCD',
    dateOfBirth: '1980-13-41',
    membershipStatus: 'expired',
    membershipLevel: 'White Belt',
    membershipStartDate: '2022-10-01',
    renewalDate: '2024-01-01',
    billingStatus: 'past_due',
  },
  {
    id: 'stg_007',
    externalMemberId: 'DCMA-1007',
    firstName: 'Sam',
    lastName: 'Rivera',
    email: 'sam.rivera@example.com',
    phone: '+15025550114',
    dateOfBirth: '1998-12-02',
    membershipStatus: 'canceled',
    membershipType: 'Competition Team',
    membershipLevel: 'Brown Belt',
    membershipStartDate: '2020-06-22',
    renewalDate: '2025-07-01',
    billingStatus: 'closed',
    possibleExistingVyraUser: true,
  },
  {
    id: 'stg_008',
    externalMemberId: 'DCMA-1008',
    firstName: 'Nora',
    lastName: 'Singh',
    email: 'nora.singh@example.com',
    phone: '+15025550117',
    dateOfBirth: '1990-08-12',
    membershipStatus: 'active',
    membershipType: 'Unlimited',
    membershipLevel: 'Blue Belt',
    membershipStartDate: '2022-02-14',
    renewalDate: '2026-11-01',
    billingStatus: 'current',
    wantsAppAccess: true,
  },
];

