#!/usr/bin/env node
import {
  getSalesStatus,
  archiveSalesOpportunity,
  buildSalesFollowupPlans,
  buildSalesOpportunityDashboard,
  createSalesOpportunity,
  getProposalStatus,
  getSalesOpportunityTimeline,
  addSalesSource,
  approveSalesSource,
  buildSalesResearchReport,
  buildSalesSourcesReport,
  buildSalesWorkflowReport,
  buildSalesDuplicateCandidatesReport,
  buildSalesIntelligenceReport,
  buildSalesPipelineForecastReport,
  buildSalesPriorityQueueReport,
  listSalesOrganizations,
  buildSalesOrganizationReport,
  listSalesContacts,
  addSalesContact,
  updateSalesContact,
  listSalesBuyingCommittees,
  listSalesRelationshipHealth,
  listSalesRelationshipMap,
  listSalesDecisionMakers,
  listSalesOrganizationTimeline,
  listSalesContactTimeline,
  listDuplicateOrganizations,
  listDuplicateContacts,
  listSalesWorkflows,
  createSalesHandoff,
  disableSalesSource,
  enrichSalesOpportunities,
  assignSalesWorkflow,
  approveSalesHandoff,
  rejectSalesHandoff,
  blockSalesHandoff,
  completeSalesHandoff,
  archiveSalesWorkflow,
  listSalesOpportunities,
  listSalesDuplicates,
  listSalesResearchIntake,
  listSalesProposalQueue,
  listSalesSources,
  mergeSalesOpportunities,
  moveSalesOpportunityStage,
  rejectSalesSource,
  restoreSalesOpportunity,
  runSalesOutreach,
  runSalesReports,
  runSalesResearch,
  runSalesTasks,
  scoreSalesOpportunities,
  updateSalesSource,
  updateSalesOpportunity,
  updateSalesWorkflow,
  verifySalesResearch,
  validateSalesExecution,
  validateSalesReports,
  validateSalesWorkflows,
} from './sales-agent-runtime.mjs';

const command = process.argv[2] ?? 'status';

const commands = {
  status: getSalesStatus,
  research: runSalesResearch,
  reports: runSalesReports,
  outreach: runSalesOutreach,
  tasks: runSalesTasks,
  opportunities: listSalesOpportunities,
  'create-opportunity': createSalesOpportunity,
  'update-opportunity': updateSalesOpportunity,
  'move-stage': moveSalesOpportunityStage,
  timeline: getSalesOpportunityTimeline,
  score: scoreSalesOpportunities,
  followup: buildSalesFollowupPlans,
  'proposal-status': getProposalStatus,
  archive: archiveSalesOpportunity,
  restore: restoreSalesOpportunity,
  merge: mergeSalesOpportunities,
  dashboard: buildSalesOpportunityDashboard,
  sources: listSalesSources,
  'add-source': addSalesSource,
  'update-source': updateSalesSource,
  'disable-source': disableSalesSource,
  'approve-source': approveSalesSource,
  'reject-source': rejectSalesSource,
  intake: listSalesResearchIntake,
  verify: verifySalesResearch,
  duplicates: listSalesDuplicates,
  enrich: enrichSalesOpportunities,
  'research-report': buildSalesResearchReport,
  'sources-report': buildSalesSourcesReport,
  workflows: listSalesWorkflows,
  'create-handoff': createSalesHandoff,
  'update-workflow': updateSalesWorkflow,
  'assign-workflow': assignSalesWorkflow,
  'approve-handoff': approveSalesHandoff,
  'reject-handoff': rejectSalesHandoff,
  'block-handoff': blockSalesHandoff,
  'complete-handoff': completeSalesHandoff,
  'archive-workflow': archiveSalesWorkflow,
  'proposal-queue': listSalesProposalQueue,
  'workflow-report': buildSalesWorkflowReport,
  'intelligence-report': buildSalesIntelligenceReport,
  'priority-queue-report': buildSalesPriorityQueueReport,
  'duplicate-candidates-report': buildSalesDuplicateCandidatesReport,
  'pipeline-forecast-report': buildSalesPipelineForecastReport,
  organizations: listSalesOrganizations,
  'organization-report': buildSalesOrganizationReport,
  contacts: listSalesContacts,
  'add-contact': addSalesContact,
  'update-contact': updateSalesContact,
  'buying-committee': listSalesBuyingCommittees,
  'relationship-health': listSalesRelationshipHealth,
  'relationship-map': listSalesRelationshipMap,
  'decision-makers': listSalesDecisionMakers,
  'organization-timeline': listSalesOrganizationTimeline,
  'contact-timeline': listSalesContactTimeline,
  'duplicate-organizations': listDuplicateOrganizations,
  'duplicate-contacts': listDuplicateContacts,
  'workflow-validate': validateSalesWorkflows,
  'reports-validate': validateSalesReports,
  validate: validateSalesExecution,
};

if (!commands[command]) {
  console.error(`Unknown sales command: ${command}`);
  console.error(`Available commands: ${Object.keys(commands).join(', ')}`);
  process.exit(1);
}

const result = commands[command]();
console.log(JSON.stringify(result, null, 2));

if (result?.status === 'fail') {
  process.exit(1);
}
